/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ButtonGroup;
/**
 *
 * @author DELL
 */
public class FormPenjualan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPenjualan
     */
    public FormPenjualan() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        
        ButtonGroup group = new ButtonGroup();
        group.add(Tipe36);
        group.add(Tipe45);
        group.add(Tipe54);

        // default pilih tipe
        Tipe36.setSelected(true);

        // load data pertama kali
        loadDataRumah();

        
        setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InputNamaPesanan = new javax.swing.JTextField();
        InputHargaTanah = new javax.swing.JTextField();
        DropdownArea = new javax.swing.JComboBox<>();
        OutputGambar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tipe36 = new javax.swing.JRadioButton();
        Tipe45 = new javax.swing.JRadioButton();
        Tipe54 = new javax.swing.JRadioButton();
        InputHargaBangunan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InputLuasTanahAsli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        InputLuasTanahTersedia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        OutputHarga = new javax.swing.JTextField();
        InputDP = new javax.swing.JTextField();
        InputLamaCicilan = new javax.swing.JTextField();
        OutputPPN = new javax.swing.JTextField();
        OutputCicilan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnProses = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nama Pemesan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Harga Tanah/m2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Area");

        InputHargaTanah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputHargaTanahActionPerformed(evt);
            }
        });

        DropdownArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bougenville", "Melati", "Flamboyan" }));
        DropdownArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropdownAreaActionPerformed(evt);
            }
        });

        OutputGambar.setText("Gambar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setToolTipText("Form");
        jPanel1.setName("Form"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Harga Bangunan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tipe Rumah");

        Tipe36.setText("Tipe-36");
        Tipe36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipe36ActionPerformed(evt);
            }
        });

        Tipe45.setText("Tipe-45");
        Tipe45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipe45ActionPerformed(evt);
            }
        });

        Tipe54.setText("Tipe-54");
        Tipe54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipe54ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Luas Tanah Asli");

        InputLuasTanahAsli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputLuasTanahAsliActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Luas Tanah Tersedia");

        jLabel8.setText("Harga");

        jLabel9.setText("DP");

        jLabel10.setText("Lama Cicilan");

        jLabel11.setText("PPN(10%)");

        jLabel12.setText("Cicilan/bln");

        jLabel13.setText("Bulan");

        jCheckBox1.setText("Setuju");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(Tipe36)
                    .addComponent(Tipe45)
                    .addComponent(Tipe54)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(InputHargaBangunan)
                            .addComponent(InputLuasTanahAsli)
                            .addComponent(InputLuasTanahTersedia)
                            .addComponent(OutputHarga)
                            .addComponent(InputDP, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(InputLamaCicilan)
                            .addComponent(OutputPPN)
                            .addComponent(OutputCicilan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jCheckBox1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputHargaBangunan)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Tipe36)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(InputLuasTanahAsli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tipe45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipe54)
                    .addComponent(InputLuasTanahTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(OutputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(InputDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(InputLamaCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(OutputPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(OutputCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(103, 103, 103)
                                .addComponent(DropdownArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(InputHargaTanah))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addComponent(InputNamaPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(OutputGambar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputNamaPesanan)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InputHargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DropdownArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addComponent(OutputGambar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputLuasTanahAsliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputLuasTanahAsliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputLuasTanahAsliActionPerformed

    private void DropdownAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropdownAreaActionPerformed
        loadDataRumah();
    }//GEN-LAST:event_DropdownAreaActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        try {
            int hargaTanah = Integer.parseInt(InputHargaTanah.getText());
            int luas = Integer.parseInt(InputLuasTanahTersedia.getText());
            int hargaBangunan = Integer.parseInt(InputHargaBangunan.getText());

            int total = (hargaTanah * luas) + hargaBangunan;
            double ppn = total * 0.1;

            int dp = Integer.parseInt(InputDP.getText());
            int lama = Integer.parseInt(InputLamaCicilan.getText());

            double cicilan = (total + ppn - dp) / lama;

            OutputHarga.setText("Rp " + formatRupiah(total));
            OutputPPN.setText("Rp " + formatRupiah(ppn));
            OutputCicilan.setText("Rp " + formatRupiah(cicilan));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Input tidak valid!");
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            Connection conn = Koneksi.getConnection();

            String sql = "INSERT INTO datarumah (nama_pemesan, id_rumah, harga_total, dp, lama_cicilan, cicilan_per_bulan, area, tipe, luas) VALUES (?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, InputNamaPesanan.getText());
            ps.setInt(2, getIdRumah());
            ps.setDouble(3, Double.parseDouble(bersihkanRupiah(OutputHarga.getText())));
            ps.setDouble(4, Double.parseDouble(bersihkanRupiah(InputDP.getText())));
            ps.setInt(5, Integer.parseInt(InputLamaCicilan.getText()));
            ps.setDouble(6, Double.parseDouble(bersihkanRupiah(OutputCicilan.getText())));

            // TAMBAHAN
            ps.setString(7, DropdownArea.getSelectedItem().toString());
            ps.setString(8, getTipe());
            ps.setInt(9, Integer.parseInt(InputLuasTanahTersedia.getText()));

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        InputNamaPesanan.setText("");
        InputHargaTanah.setText("");
        InputHargaBangunan.setText("");
        InputLuasTanahAsli.setText("");
        InputLuasTanahTersedia.setText("");
        InputDP.setText("");
        InputLamaCicilan.setText("");
        OutputHarga.setText("");
        OutputPPN.setText("");
        OutputCicilan.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void Tipe36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipe36ActionPerformed
        InputLuasTanahAsli.setText("90");
        loadDataRumah();
    }//GEN-LAST:event_Tipe36ActionPerformed

    private void Tipe45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipe45ActionPerformed
        InputLuasTanahAsli.setText("120");
        loadDataRumah();
    }//GEN-LAST:event_Tipe45ActionPerformed

    private void Tipe54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipe54ActionPerformed
        InputLuasTanahAsli.setText("140");
        loadDataRumah();
    }//GEN-LAST:event_Tipe54ActionPerformed

    private void InputHargaTanahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputHargaTanahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputHargaTanahActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if (jCheckBox1.isSelected()) {
            JOptionPane.showMessageDialog(this, "Pelanggan konfirmasi setuju");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenjualan().setVisible(true);
            }
        });
    }

    private String bersihkanRupiah(String text) {
        return text
            .replace("Rp", "")
            .replace(".", "")
            .replace(",", ".") 
            .trim();
    }
    private void loadDataRumah() {
    try {
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT * FROM rumah WHERE area=? AND tipe=?";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, DropdownArea.getSelectedItem().toString());
        ps.setString(2, getTipe());

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            InputHargaTanah.setText(rs.getString("harga_tanah"));
            InputHargaBangunan.setText(rs.getString("harga_bangunan"));
            InputLuasTanahAsli.setText(rs.getString("luas_tanah"));
            InputLuasTanahTersedia.setText(rs.getString("luas_tanah"));

            String filename = rs.getString("gambar"); 

            String base = new java.io.File("").getAbsolutePath();
            String path = base + "/src/images/" + filename;

            System.out.println("PATH: " + path);
            System.out.println("EXISTS: " + new java.io.File(path).exists());

            ImageIcon icon = new ImageIcon(path);

            if (icon.getIconWidth() == -1) {
                System.out.println("Gagal load gambar: " + path);
                OutputGambar.setText("Gambar tidak ditemukan");
                OutputGambar.setIcon(null);
            } else {
                Image img = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                OutputGambar.setIcon(new ImageIcon(img));
                OutputGambar.setText("");
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    private String getTipe() {
        if (Tipe36.isSelected()) return "T36";
        if (Tipe45.isSelected()) return "T45";
        if (Tipe54.isSelected()) return "T54";
        return "-";
    }
    private int getIdRumah() {
        int id = 0;
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT id_rumah FROM rumah WHERE area=?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, DropdownArea.getSelectedItem().toString());

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                id = rs.getInt("id_rumah");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        return id;
    }
    private String formatRupiah(double angka) {
        Locale indonesia = new Locale("id", "ID");
        NumberFormat rupiah = NumberFormat.getInstance(indonesia);
        return rupiah.format(angka);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DropdownArea;
    private javax.swing.JTextField InputDP;
    private javax.swing.JTextField InputHargaBangunan;
    private javax.swing.JTextField InputHargaTanah;
    private javax.swing.JTextField InputLamaCicilan;
    private javax.swing.JTextField InputLuasTanahAsli;
    private javax.swing.JTextField InputLuasTanahTersedia;
    private javax.swing.JTextField InputNamaPesanan;
    private javax.swing.JTextField OutputCicilan;
    private javax.swing.JLabel OutputGambar;
    private javax.swing.JTextField OutputHarga;
    private javax.swing.JTextField OutputPPN;
    private javax.swing.JRadioButton Tipe36;
    private javax.swing.JRadioButton Tipe45;
    private javax.swing.JRadioButton Tipe54;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
